function createChapterSix(api) {
  const T=three_module_exports,{scene,kit,stylized,lampTemplate,state,camera,keys,avatar,capsule,collide,setActor,toast,chime}=api;
  const offset=new T.Vector3(120,0,-50),root=new T.Group(),architecture=new T.Group();root.name='Sixth chapter - Divided light';root.position.copy(offset);root.add(architecture);scene.add(root);
  const mats=new Map();kit.traverse(o=>{if(o.isMesh)mats.set(o.material.name,o.material);});
  const stone=mats.get('brick-stone'),trim=mats.get('trim-stone'),floor=(mats.get('tiles-gray')||stone).clone(),metal=new T.MeshStandardMaterial({color:0x929783,roughness:.5,metalness:.55});
  if(floor.map){floor.map=floor.map.clone();floor.map.wrapS=floor.map.wrapT=T.RepeatWrapping;floor.map.repeat.set(2,2);}
  const proxyRoot=new T.Group();proxyRoot.position.copy(offset);
  const world=p=>p.clone().add(offset),localActor=()=>state.actor.clone().sub(offset);
  function box(size,p,material=stone,parent=architecture){const m=new T.Mesh(new T.BoxGeometry(...size),material);m.position.set(...p);m.castShadow=m.receiveShadow=true;parent.add(m);return m;}
  function proxy(min,max,parent=proxyRoot){return box(max.map((v,i)=>v-min[i]),max.map((v,i)=>(v+min[i])/2),new T.MeshBasicMaterial(),parent);}
  function instance(lib,name,p,scale,rotation=0){const source=lib.getObjectByName(name);if(!source)throw Error('Missing asset '+name);const g=source.clone(true);g.position.set(...p);g.scale.setScalar(scale);g.rotation.y=rotation;g.traverse(o=>{if(o.isMesh)o.castShadow=o.receiveShadow=true;});architecture.add(g);return g;}
  const floors=[[-2.6,1.8,2.6,5.4],[-3.5,-4.6,3.5,2.3],[-10.5,-5.6,-6.5,1.2],[6.5,-6.6,10.5,1.2]];
  for(const [x0,z0,x1,z1] of floors){box([x1-x0,.3,z1-z0],[(x0+x1)/2,-.16,(z0+z1)/2],floor);proxy([x0,-.4,z0],[x1,0,z1]);}
  function wall(min,max){box(max.map((v,i)=>v-min[i]),max.map((v,i)=>(v+min[i])/2));proxy(min,max);}
  wall([-.8,0,1.15],[2.8,3.1,1.55]);
  wall([-8.3,0,-3.4],[-7.9,3.6,-.65]);wall([-8.3,0,.7],[-7.9,3.6,1.8]);box([.4,1.2,1.35],[-8.1,3,.025],trim);
  for(const x of [-10.55,10.55])wall([x-.15,0,-5.6],[x+.15,.65,1.25]);
  wall([-10.5,0,-5.75],[-6.4,.65,-5.45]);wall([6.4,0,-6.7],[10.5,.65,-6.4]);
  for(const [x,z,s] of [[0,2.9,.32],[0,-1.7,.43],[-8.5,-2.2,.4],[8.5,-2.2,.42]])instance(kit,'terrace',[x,-s*9.6,z],s);
  instance(kit,'blue_window',[.5,0,.85],.23);instance(kit,'broken_arch',[-10.5,0,-2.6],.27,Math.PI/2);
  instance(kit,'rose_wall',[0,0,-5],.2,Math.PI/2);instance(kit,'broken_arch',[8.55,0,-6.65],.28);
  instance(stylized,'banner',[-8.5,1.1,-3.4],.55,Math.PI/2);
  for(const [x,y,z,s] of [[.1,1.3,1,.7],[-8.4,1.5,-3,.7],[8.5,1.4,-6.2,.8]])instance(stylized,'ivy',[x,y,z],s);
  for(const [x,z] of [[-2.4,4.8],[2.9,-4.1],[-10,.6],[-9.9,-5.1],[10,-3.7],[7,-6.1]])instance(kit,'foliage',[x,.02,z],.2,x);
  for(const [x,z] of [[-2.8,2.3],[-9.9,-.3],[10.1,-5.2]]){instance(stylized,'torch',[x,0,z],.52);const l=new T.PointLight(0xffc58a,18,7,2);l.position.set(x,1.5,z);root.add(l);}
  const lift={position:new T.Vector3(0,0,-2.8),previous:new T.Vector3(0,0,-2.8),height:2.4,half:[1.6,1.3],group:new T.Group()};root.add(lift.group);lift.group.position.copy(lift.position);
  box([3.2,.32,2.6],[0,-.17,0],stone,lift.group);box([3.12,.04,2.52],[0,-.015,0],floor,lift.group);
  for(const [side,color] of [[-1,0x76baff],[1,0x72e39f]]){const geometry=new T.BufferGeometry().setAttribute('position',new T.Float32BufferAttribute([side*1.3,.03,0,side*.9,.03,-.23,side*.9,.03,.23],3));lift.group.add(new T.Mesh(geometry,new T.MeshBasicMaterial({color,side:T.DoubleSide})));}
  const liftCollision=new T.Group();proxy([-1.6,-.34,-1.3],[1.6,0,1.3],liftCollision);lift.tree=new Octree().fromGraphNode(liftCollision);
  for(const x of [-1.75,1.75]){box([.09,2.7,.09],[x,1.2,-3.85],metal);box([.2,.15,.25],[x,2.55,-3.85],trim);}
  const receiverPositions=[new T.Vector3(-7.6,2.4+MECHANISM_Y,-2.8),new T.Vector3(7.6,2.4+MECHANISM_Y,-2.8)],bits=[4,2],colors=[0x75baff,0x6fe69b];
  const receivers=receiverPositions.map((p,i)=>{box([1.05,2.4,1.05],[p.x,1.2,p.z]);proxy([p.x-.525,0,p.z-.525],[p.x+.525,2.4,p.z+.525]);const built=buildMechanism({box,proxy,position:p,color:colors[i],stone,trim,parent:root,baseY:2.4});const target=new T.Mesh(new T.SphereGeometry(.36,12,8),new T.MeshBasicMaterial({visible:false}));target.position.copy(p);target.userData.noLand=true;root.add(target);const wire=new T.Line(new T.BufferGeometry().setFromPoints([p.clone(),new T.Vector3(i?6.6:-6.6,.025,-2.8),new T.Vector3(i?3.5:-3.5,.025,-2.8)]),new T.LineBasicMaterial({color:0x3b6173}));root.add(wire);return {target,gem:built.crystal,light:built.light,wire};});
  const bridges=[],bridgeTrees=[];
  for(const [x0,x1,z0,z1] of [[-6.6,-3.4,-4,-1.6],[3.4,6.6,-4,-1.6],[-6.6,-3.4,0,1.2]]){const g=new T.Group();root.add(g);box([x1-x0,.32,z1-z0],[(x0+x1)/2,-.17,(z0+z1)/2],stone,g);box([x1-x0-.06,.04,z1-z0-.06],[(x0+x1)/2,-.015,(z0+z1)/2],floor,g);g.position.y=-1.35;bridges.push(g);const pg=new T.Group();pg.position.copy(offset);proxy([x0,-.4,z0],[x1,0,z1],pg);bridgeTrees.push(new Octree().fromGraphNode(pg));}
  const gate=new T.Group(),shortcutGate=new T.Group();root.add(gate,shortcutGate);
  for(let i=0;i<14;i++)box([.06,2.3,.1],[6.6+i*.29,1.15,-4.4],metal,gate);for(const y of [.3,1.7])box([4,.08,.12],[8.5,y,-4.4],metal,gate);
  for(let i=0;i<6;i++)box([.1,2.35,.055],[-8.1,1.17,-.57+i*.23],metal,shortcutGate);
  const gatesProxy=new T.Group();gatesProxy.position.copy(offset);const gateProxy=proxy([6.5,0,-4.6],[10.5,2.5,-4.2],gatesProxy),shortcutProxy=proxy([-8.3,0,-.65],[-7.9,2.4,.7],gatesProxy);const gateTree=new Octree().fromGraphNode(gatesProxy);
  const buttonPositions=[new T.Vector3(-2.2,.42,-1),new T.Vector3(-9.3,.42,.15)];
  const buttons=buttonPositions.map((p,i)=>{box([.65,.35,.65],[p.x,.175,p.z],trim);proxy([p.x-.325,0,p.z-.325],[p.x+.325,.43,p.z+.325]);const cap=new T.Mesh(new T.CylinderGeometry(.22,.24,.13,8),new T.MeshStandardMaterial({color:i?0xd8b57b:0xc7e0e5,emissive:i?0x6b4b20:0x243b42,emissiveIntensity:.25,metalness:.4,roughness:.35}));cap.position.copy(p);root.add(cap);return cap;});
  const particlePositions=new Float32Array(24*3);for(let i=0;i<24;i++){particlePositions[i*3]=Math.cos(i*2.4)*.4;particlePositions[i*3+1]=(i%7)*.08;particlePositions[i*3+2]=Math.sin(i*2.4)*.4;}
  const particles=new T.Points(new T.BufferGeometry().setAttribute('position',new T.BufferAttribute(particlePositions,3)),new T.PointsMaterial({color:0xffd59c,size:.04,transparent:true,opacity:0,depthWrite:false,blending:T.AdditiveBlending}));particles.position.copy(buttonPositions[1]);root.add(particles);
  const lamp={pos:new T.Vector3(-2,GROUND_Y,2.8),home:new T.Vector3(-2,GROUND_Y,2.8),aim:new T.Vector3(-1,0,0),mode:'home',side:0,relative:new T.Vector3(),fall:{v:0},mask:6};
  lamp.visual=lampTemplate.clone(true);lamp.visual.visible=true;lamp.visual.userData.noLand=true;lamp.visual.traverse(o=>{if(o.isMesh){o.material=o.material.clone();if(o.material.emissive&&o.material.emissive.r+o.material.emissive.g+o.material.emissive.b>.01){o.material.color.setHex(0x79e5ec);o.material.emissive.setHex(0x79e5ec);}}});root.add(lamp.visual);
  lamp.beam=new T.Mesh(new T.CylinderGeometry(.027,.027,1,8),new T.MeshBasicMaterial({color:0x75e0f1,toneMapped:false}));lamp.beam.userData.noLand=true;root.add(lamp.beam);
  const goal=new T.Mesh(new T.TorusGeometry(.6,.025,8,40),new T.MeshBasicMaterial({color:0xc3edda}));goal.rotation.x=-Math.PI/2;goal.position.set(8.6,.03,-5.7);root.add(goal);
  root.updateMatrixWorld(true);const staticTree=new Octree().fromGraphNode(proxyRoot);
  const buckets=new Map(),remove=[];architecture.traverse(o=>{if(!o.isMesh)return;const geometry=o.geometry.index?o.geometry.toNonIndexed():o.geometry.clone();geometry.applyMatrix4(o.matrixWorld).translate(-offset.x,-offset.y,-offset.z);const key=o.material.uuid+Object.keys(geometry.attributes).sort().join(',');if(!buckets.has(key))buckets.set(key,{material:o.material,geometries:[]});buckets.get(key).geometries.push(geometry);remove.push(o);});remove.forEach(o=>o.removeFromParent());for(const {material,geometries} of buckets.values()){const m=new T.Mesh(mergeGeometries(geometries),material);m.castShadow=m.receiveShadow=true;architecture.add(m);geometries.forEach(g=>g.dispose());}
  const opticalTree=createOpticalTree(architecture),ray=new T.Raycaster(),data={held:-1,power:[false,false],liftTarget:0,latched:false,gate:0,bridges:[0,0,0],cooldowns:[0,0],burst:0,rider:false,done:false,falls:0,evasions:0};let vy=0;
  function canReach(from,to){const d=to.clone().sub(from),length=d.length();if(length<.001)return true;ray.set(world(from),d.normalize());let hit=opticalTree.rayIntersect(ray.ray);if(hit&&hit.distance<length-.08)return false;if(data.gate<.85){const g=ray.intersectObjects([gateProxy,shortcutProxy],false)[0];if(g&&g.distance<length-.08)return false;}return true;}
  function action(){if(state.paused||data.done)return null;const p=localActor(),eye=p.clone().add(new T.Vector3(0,CARRY_Y,0));let nearest=null,distance=1.55;buttons.forEach((b,i)=>{const d=eye.distanceTo(buttonPositions[i]);if(d<distance&&canReach(eye,buttonPositions[i])){nearest={kind:'button',index:i};distance=d;}});if(nearest)return nearest;if(data.held===0)return {kind:'drop'};return eye.distanceTo(lamp.pos)<1.65&&canReach(eye,lamp.pos)?{kind:'pickup'}:null;}
  function press(index){if(data.cooldowns[index]>0)return false;data.cooldowns[index]=.3;if(index===0){data.liftTarget=data.liftTarget>0?0:lift.height;toast(data.liftTarget?'灯台升起':'灯台下降');}else if(!data.latched){data.latched=true;data.burst=1.2;toast('门闩松开，侧廊捷径展开');}chime(index?760:510);return true;}
  function interact(){const a=action();if(!a)return false;if(a.kind==='button')return press(a.index);if(a.kind==='pickup'){data.held=0;lamp.mode='carried';state.lampMode='carried';}else{const p=world(lamp.pos);api.beginFall(p,lamp.aim);lamp.pos.copy(p).sub(offset);lamp.mode='falling';lamp.fall.v=0;data.held=-1;state.lampMode='home';}trace();return true;}
  function aim(point){if(data.held!==0)return;lamp.aim.copy(point).sub(localActor()).setY(0).normalize();avatar.rotation.y=Math.atan2(lamp.aim.x,lamp.aim.z);}
  function trace(){
    if(lamp.mode==='platform'){lamp.pos.copy(lift.position).add(lamp.relative);lamp.aim.copy(receiverPositions[lamp.side]).sub(lamp.pos).setY(0).normalize();}
    else if(lamp.mode==='carried'){if(api.handCarry(lamp.pos)){lamp.pos.y=state.actor.y+CARRY_Y;lamp.pos.sub(offset);}else lamp.pos.copy(localActor()).add(new T.Vector3(lamp.aim.x*.42,CARRY_Y,lamp.aim.z*.42));const anchor=localActor().add(new T.Vector3(0,CARRY_Y,0)),delta=lamp.pos.clone().sub(anchor),distance=delta.length();if(distance>.001){ray.set(world(anchor),delta.normalize());const hit=opticalTree.rayIntersect(ray.ray);if(hit&&hit.distance<distance)lamp.pos.copy(anchor).addScaledVector(delta,Math.max(0,hit.distance-.2));}}
    lamp.visual.position.copy(lamp.pos);lamp.visual.scale.setScalar(.65);lamp.visual.quaternion.setFromUnitVectors(api.originalLampDirection,lamp.aim);root.updateMatrixWorld(true);const start=lamp.pos.clone().addScaledVector(lamp.aim,.1);ray.set(world(start),lamp.aim);ray.far=25;let hit=ray.intersectObjects([...receivers.map(r=>r.target),...(data.gate<.85?[gateProxy,shortcutProxy]:[])],false)[0];const geo=opticalTree.rayIntersect(ray.ray);if(geo&&geo.distance<25&&(!hit||geo.distance<hit.distance))hit={object:null,point:geo.position,distance:geo.distance};data.power=receivers.map((r,i)=>hit?.object===r.target&&(lamp.mask&bits[i])===bits[i]);const end=hit?hit.point.clone().sub(offset):start.clone().addScaledVector(lamp.aim,25);lamp.beam.position.copy(start).add(end).multiplyScalar(.5);lamp.beam.scale.y=start.distanceTo(end);lamp.beam.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),lamp.aim);receivers.forEach((r,i)=>{r.gem.material.emissiveIntensity=data.power[i]?1:.12;r.light.intensity=data.power[i]?4:.4;r.wire.material.color.setHex(data.power[i]?colors[i]:0x3b6173);});return data.power;
  }
  function collideLift(){const p=world(lift.position);capsule.translate(p.clone().negate());let ground=false;for(let i=0;i<3;i++){const hit=lift.tree.capsuleIntersect(capsule);if(!hit)break;ground ||=hit.normal.y>.5;capsule.translate(hit.normal.multiplyScalar(hit.depth));}capsule.translate(p);return ground;}
  function reset(){Object.assign(data,{held:-1,power:[false,false],liftTarget:0,latched:false,gate:0,bridges:[0,0,0],cooldowns:[0,0],burst:0,rider:false,done:false,falls:0,evasions:0});vy=0;state.won=state.paused=false;state.lampMode='home';keys.clear();lift.position.set(0,0,-2.8);lift.previous.copy(lift.position);lift.group.position.copy(lift.position);lamp.mode='home';lamp.mask=6;lamp.pos.copy(lamp.home);lamp.aim.set(0,-.4,-1).normalize();lamp.fall.v=0;gate.position.y=shortcutGate.position.y=0;bridges.forEach(g=>g.position.y=-1.35);setActor(world(new T.Vector3(0,0,4.8)));document.getElementById('overlay').hidden=true;trace();}
  function tick(dt){
    if(state.paused)return;data.cooldowns=data.cooldowns.map(t=>Math.max(0,t-dt));buttons.forEach((b,i)=>b.position.y=buttonPositions[i].y-.08*data.cooldowns[i]/.3);data.burst=Math.max(0,data.burst-dt);particles.material.opacity=data.burst*.55;particles.position.y=buttonPositions[1].y+(1.2-data.burst)*.65;
    lift.previous.copy(lift.position);lift.position.y+=T.MathUtils.clamp(data.liftTarget-lift.position.y,-dt*1.2,dt*1.2);lift.group.position.copy(lift.position);const actor=localActor();if(!data.rider&&lift.position.y<lift.previous.y&&Math.abs(actor.x)<1.8&&Math.abs(actor.z+2.8)<1.5&&lift.position.y-.32<actor.y+1.3&&lift.position.y>actor.y+.15){vy=0;data.evasions++;setActor(world(new T.Vector3(-2.8,0,.5)));}if(data.rider)capsule.translate(lift.position.clone().sub(lift.previous));
    const forward=camera.getWorldDirection(new T.Vector3()).setY(0).normalize(),right=new T.Vector3().crossVectors(forward,new T.Vector3(0,1,0)),move=new T.Vector3();if(keys.has('KeyW')||keys.has('ArrowUp'))move.add(forward);if(keys.has('KeyS')||keys.has('ArrowDown'))move.sub(forward);if(keys.has('KeyD')||keys.has('ArrowRight'))move.add(right);if(keys.has('KeyA')||keys.has('ArrowLeft'))move.sub(right);if(move.lengthSq()){move.normalize();avatar.rotation.y=Math.atan2(move.x,move.z);if(data.held===0)lamp.aim.copy(move);}const speed=keys.has('ShiftLeft')?3.7:2.6;vy-=18*dt;capsule.translate(new T.Vector3(move.x*speed*dt,vy*dt,move.z*speed*dt));let grounded=collide(staticTree);grounded=collideLift()||grounded;bridgeTrees.forEach((tree,i)=>{if(data.bridges[i]>.94)grounded=collide(tree)||grounded;});if(data.gate<.85)grounded=collide(gateTree)||grounded;if(grounded)vy=Math.max(0,vy);state.actor.copy(capsule.start).sub(new T.Vector3(0,.24,0));avatar.position.copy(state.actor);const p=localActor();data.rider=Math.abs(p.y-lift.position.y)<.06&&Math.abs(p.x)<1.5&&Math.abs(p.z+2.8)<1.2;
    if(p.y< -1.8){data.falls++;data.rider=false;vy=0;setActor(world(new T.Vector3(0,0,4.8)));toast('回到入口，门闩与光源布置保留');}
    if(lamp.mode==='falling'){root.updateMatrixWorld(true);const wp=world(lamp.pos),result=api.stepFall(wp,lamp.fall,dt);lamp.pos.copy(wp).sub(offset);if(result==='landed'){const rel=lamp.pos.clone().sub(lift.position);lamp.mode='ground';if(Math.abs(rel.x)<1.6&&Math.abs(rel.z)<1.3&&rel.y>.1&&rel.y<.65){lamp.mode='platform';lamp.relative.copy(rel);lamp.side=rel.x<0?0:1;}const target=receiverPositions[lamp.pos.x<0?0:1];lamp.aim.copy(target).sub(lamp.pos).setY(0).normalize();}else if(result==='lost'){lamp.mode='home';lamp.pos.copy(lamp.home);lamp.aim.set(0,-.4,-1).normalize();toast('青光回到入口');}}
    trace();const desired=[data.power[0]?1:0,data.power[1]?1:0,data.latched?1:0];data.bridges.forEach((v,i)=>{data.bridges[i]+=T.MathUtils.clamp(desired[i]-v,-dt/1.2,dt/1.2);bridges[i].position.y=-1.35*(1-data.bridges[i]);});data.gate+=T.MathUtils.clamp((data.latched?1:0)-data.gate,-dt/.8,dt/.8);gate.position.y=shortcutGate.position.y=-2.7*data.gate;
    if(data.latched&&data.power[1]&&data.bridges[1]>.94&&p.x>7&&p.x<10.3&&p.z< -5.3&&p.y>-.2){data.done=true;state.paused=state.won=true;keys.clear();api.finish();}
  }
  function hud(){const $=id=>document.getElementById(id);$('objective').textContent=data.latched?(data.power[1]?'穿过右廊大门':'返回中庭，重新配置青光'):(data.power[0]?'探索左廊，开启门闩':'将青光送到上方蓝机关');$('power').querySelector('span').textContent=`蓝 ${data.power[0]?'亮':'暗'} · 绿 ${data.power[1]?'亮':'暗'} · 门闩 ${data.latched?'已开':'未开'}`;$('power').classList.toggle('on',data.latched&&data.power[1]);$('lampState').textContent=data.held===0?'青光 · 随身':lamp.mode==='platform'?`青光 · ${lamp.side?'朝右':'朝左'}`:'青光待命';$('inventory').classList.toggle('active',data.held===0);setColorOrbits(data.held===0||data.power.some(Boolean)?6:0);$('location').textContent=pZone();const a=action();$('context').style.display=a?'block':'none';$('interact').textContent=a?.kind==='button'?(a.index===0?(data.liftTarget?'降下灯台':'升起灯台'):(data.latched?'门闩已开启':'开启门闩')):a?.kind==='pickup'?'提起青光':'放下青光';}
  function pZone(){const p=localActor();return p.x< -6.4?'蓝纹藏廊':p.x>6.4?'绿光归廊':'双廊灯庭';}
  return {root,offset,data,lamp,lamps:[lamp],lift,bridges,buttons,buttonPositions,receiverPositions,world,localActor,reset,tick,trace,interact,aim,hud,goal:world(new T.Vector3(8.6,.6,-5.7)),introFocus:world(new T.Vector3(-2.2,.7,-1)),focus(){if(data.held===0)aim(receiverPositions[localActor().x<0?0:1]);}};
}
