function createChapterFour(api) {
  const T=three_module_exports;
  const {scene,kit,stylized,lampTemplate,state,camera,keys,avatar,capsule,collide,setActor,toast,chime}=api;
  const offset=new T.Vector3(72,0,-30),root=new T.Group(),architecture=new T.Group();
  root.name='Fourth chapter - White light relay';root.position.copy(offset);root.add(architecture);scene.add(root);
  const mats=new Map();kit.traverse(o=>{if(o.isMesh)mats.set(o.material.name,o.material);});
  const stone=mats.get('brick-stone'),trim=mats.get('trim-stone'),floor=(mats.get('tiles-gray')||stone).clone();
  if(floor.map){floor.map=floor.map.clone();floor.map.wrapS=floor.map.wrapT=T.RepeatWrapping;floor.map.repeat.set(2,2);}
  const proxyRoot=new T.Group();proxyRoot.position.copy(offset);
  const floors=[[-4,0,4,5.3],[-3.5,-7.4,3.5,-3.25],[-3.3,-16.2,3.3,-10.65]];
  function box(size,p,material=stone,parent=architecture){const m=new T.Mesh(new T.BoxGeometry(...size),material);m.position.set(...p);m.castShadow=m.receiveShadow=true;parent.add(m);return m;}
  function proxy(min,max,parent=proxyRoot){return box(max.map((v,i)=>v-min[i]),max.map((v,i)=>(v+min[i])/2),new T.MeshBasicMaterial(),parent);}
  function instance(lib,name,p,scale,rotation=0){const source=lib.getObjectByName(name);if(!source)throw Error('Missing asset '+name);const g=source.clone(true);g.position.set(...p);g.scale.setScalar(scale);g.rotation.y=rotation;g.traverse(o=>{if(o.isMesh)o.castShadow=o.receiveShadow=true;});architecture.add(g);return g;}
  for(const [x0,z0,x1,z1] of floors){
    box([x1-x0,.28,z1-z0],[(x0+x1)/2,-.15,(z0+z1)/2],floor);proxy([x0,-.4,z0],[x1,0,z1]);
    for(const x of [x0-.1,x1+.1]){box([.35,.6,z1-z0],[x,.23,(z0+z1)/2]);box([.46,.1,z1-z0],[x,.59,(z0+z1)/2],trim);proxy([x-.18,0,z0],[x+.18,.66,z1]);}
    instance(kit,'terrace',[(x0+x1)/2,-3.5,(z0+z1)/2],.36);
    for(const z of [z0,z1])for(const side of [-1,1]){const width=(x1-x0)/2-1.2,x=side*(1.2+width/2);box([width,.58,.34],[x,.23,z]);proxy([x-width/2,0,z-.17],[x+width/2,.6,z+.17]);}
  }
  instance(kit,'broken_arch',[-4.1,0,1.1],.27,Math.PI/2);
  instance(kit,'rose_wall',[4.2,0,-5.8],.24,Math.PI/2);
  instance(kit,'blue_window',[-3.9,0,-6.4],.23,.2);
  instance(kit,'broken_arch',[0,0,-16.35],.37);
  instance(stylized,'banner',[3.9,.65,-5.4],.65,0);
  for(const [x,y,z,s] of [[-4.1,1,1.2,.8],[4.2,1.5,-6,.85],[-1.6,1.1,-16,.8],[1.7,2,-16,.6]])instance(stylized,'ivy',[x,y,z],s);
  for(const [x,z] of [[-3.5,4.5],[3.4,4.5],[-3,-3.8],[3,-6.8],[-2.8,-11.3],[2.7,-15.4]])instance(kit,'foliage',[x,.01,z],.2,x);
  for(const [x,z] of [[4.05,2],[-3.65,-4.8],[3.45,-12.4]]){instance(stylized,'torch',[x,0,z],.55);const light=new T.PointLight(0xffbc7b,19,7,2);light.position.set(x,1.6,z);root.add(light);}
  const rearLight=new T.PointLight(0xbce9ff,14,8,2);rearLight.position.set(0,3,-15);root.add(rearLight);
  const requirements=[2,6,7],receiverPositions=[new T.Vector3(-2,MECHANISM_Y,.7),new T.Vector3(-1.9,MECHANISM_Y,-6.4),new T.Vector3(-1.9,MECHANISM_Y,-13.25)];
  const receiverColors=[0x6dea8b,0x67e0ec,0xe5f3ff];
  const receivers=receiverPositions.map((p,i)=>{
    const built=buildMechanism({box,proxy,position:p,color:receiverColors[i],stone,trim,parent:root});
    const target=new T.Mesh(new T.SphereGeometry(.38,12,8),new T.MeshBasicMaterial({visible:false}));target.position.copy(p);target.userData.noLand=true;root.add(target);
    const gem=built.crystal,light=built.light;
    const z=i===0?-.1:i===1?-7.5:-14.1;const wire=new T.Line(new T.BufferGeometry().setFromPoints([new T.Vector3(p.x,.025,p.z),new T.Vector3(p.x,.025,z),new T.Vector3(0,.025,z)]),new T.LineBasicMaterial({color:0x40565f}));root.add(wire);return {target,gem,light,wire};
  });
  // 不再有固定灯座：青光与白光开局就直接摆在能照到前桥、后桥的地面上，玩家可随时挪走
  const definitions=[{name:'绿',mask:2,color:0x6dea8b,home:[0,GROUND_Y,3.8]},{name:'青',mask:6,color:0x67e0ec,home:[-2.1,GROUND_Y,3.4],start:{x:-2.1,z:3.4,target:0}},{name:'白',mask:7,color:0xe5f3ff,home:[-1.9,GROUND_Y,-4.55],start:{x:-1.9,z:-4.55,target:1}}];
  const lamps=definitions.map((d,id)=>{const visual=lampTemplate.clone(true);visual.visible=true;visual.userData.noLand=true;visual.traverse(o=>{if(o.isMesh){o.material=o.material.clone();if(o.material.emissive&&o.material.emissive.r+o.material.emissive.g+o.material.emissive.b>.01){o.material.emissive.setHex(d.color);o.material.color.setHex(d.color);}}});root.add(visual);const beam=new T.Mesh(new T.CylinderGeometry(.026,.026,1,8),new T.MeshBasicMaterial({color:d.color,toneMapped:false}));beam.userData.noLand=true;root.add(beam);return {...d,id,home:new T.Vector3(...d.home),pos:new T.Vector3(...d.home),aim:new T.Vector3(0,-.4,1).normalize(),visual,beam,mode:'home',target:-1,fall:{v:0}};});
  const bridgeRanges=[[-3.3,.05],[-10.7,-7.35]],bridgeGroups=[],bridgeTrees=[];
  for(const [a,b] of bridgeRanges){const group=new T.Group();root.add(group);box([2.4,.32,b-a],[0,-.17,(a+b)/2],stone,group);box([2.32,.04,b-a-.04],[0,-.015,(a+b)/2],floor,group);bridgeGroups.push(group);const pr=new T.Group();pr.position.copy(offset);proxy([-1.2,-.4,a],[1.2,0,b],pr);bridgeTrees.push(new Octree().fromGraphNode(pr));}
  const gate=new T.Group();root.add(gate);const metal=new T.MeshStandardMaterial({color:0x849293,metalness:.6,roughness:.4});for(let i=0;i<21;i++)box([.055,2.3,.09],[-3.15+i*.315,1.15,-14.1],metal,gate);for(const y of [.3,1.8])box([6.5,.08,.12],[0,y,-14.1],metal,gate);
  const gateRoot=new T.Group();gateRoot.position.copy(offset);const gateProxy=proxy([-3.3,0,-14.35],[3.3,2.5,-13.85],gateRoot),gateTree=new Octree().fromGraphNode(gateRoot);
  const goal=new T.Mesh(new T.TorusGeometry(.6,.026,8,40),new T.MeshBasicMaterial({color:0xeaf8ff}));goal.rotation.x=-Math.PI/2;goal.position.set(0,.03,-15.35);root.add(goal);
  root.updateMatrixWorld(true);const staticTree=new Octree().fromGraphNode(proxyRoot);
  const buckets=new Map(),remove=[];architecture.traverse(o=>{if(!o.isMesh)return;const g=o.geometry.index?o.geometry.toNonIndexed():o.geometry.clone();g.applyMatrix4(o.matrixWorld).translate(-offset.x,-offset.y,-offset.z);const key=o.material.uuid+Object.keys(g.attributes).sort().join(',');if(!buckets.has(key))buckets.set(key,{material:o.material,geometries:[]});buckets.get(key).geometries.push(g);remove.push(o);});remove.forEach(o=>o.removeFromParent());for(const {material,geometries} of buckets.values()){const m=new T.Mesh(mergeGeometries(geometries),material);m.castShadow=m.receiveShadow=true;architecture.add(m);geometries.forEach(g=>g.dispose());}
  const opticalTree=createOpticalTree(architecture),ray=new T.Raycaster(),data={held:-1,masks:[0,0,0],power:[false,false,false],bridges:[1,1],gate:0,done:false,falls:0};let vy=0;
  const localActor=()=>state.actor.clone().sub(offset),world=p=>p.clone().add(offset);
  function action(){if(state.paused||data.done)return null;const p=localActor();if(data.held>=0)return {kind:'drop'};let found=-1,d=1.65;for(const l of lamps){const dist=Math.hypot(p.x-l.pos.x,p.z-l.pos.z);if(dist<d){found=l.id;d=dist;}}return found<0?null:{kind:'pickup',lamp:found};}
  function interact(){const a=action();if(!a)return false;if(a.kind==='pickup'){const l=lamps[a.lamp];data.held=l.id;l.mode='carried';l.target=-1;state.lampMode='carried';toast(`拾起${l.name}光`);}else{const l=lamps[data.held];const aimed=nearestVisibleTarget(l.pos,receiverPositions,ray,opticalTree,world);l.target=aimed?receiverPositions.indexOf(aimed):-1;if(aimed){l.aim.copy(aimed).sub(l.pos);l.aim.y=0;l.aim.normalize();}const p=world(l.pos);api.beginFall(p,l.aim);l.pos.copy(p).sub(offset);l.mode='falling';l.fall.v=0;data.held=-1;state.lampMode='home';}trace();chime(550);return true;}
  function aim(p){if(data.held<0)return;const l=lamps[data.held];l.aim.copy(p).sub(localActor()).setY(0).normalize();avatar.rotation.y=Math.atan2(l.aim.x,l.aim.z);}
  function trace(){const masks=[0,0,0];for(const l of lamps){
    if(l.mode==='carried'){if(api.firstPersonCarry(l.pos,l.aim)){l.pos.sub(offset);l.visual.scale.setScalar(api.firstPersonCarry.scale);}else if(api.handCarry(l.pos)){l.pos.sub(offset);l.visual.scale.setScalar(.65);}else l.pos.copy(localActor()).add(new T.Vector3(l.aim.x*.42,CARRY_Y,l.aim.z*.42));}else l.visual.scale.setScalar(.65);
    l.visual.position.copy(l.pos);l.visual.quaternion.setFromUnitVectors(api.originalLampDirection,l.aim);root.updateMatrixWorld(true);const start=world(l.pos).addScaledVector(l.aim,.1);ray.set(start,l.aim);ray.far=24;
    let hit=ray.intersectObjects([...receivers.map(r=>r.target),...(data.gate<.85?[gateProxy]:[])],false)[0];const geometry=opticalTree.rayIntersect(ray.ray);if(geometry&&geometry.distance<24&&(!hit||geometry.distance<hit.distance))hit={object:null,point:geometry.position,distance:geometry.distance};receivers.forEach((r,i)=>{if(hit?.object===r.target)masks[i]|=l.mask;});
    const begin=l.pos.clone().addScaledVector(l.aim,.1),end=hit?hit.point.clone().sub(offset):l.pos.clone().addScaledVector(l.aim,24);l.beam.position.copy(begin).add(end).multiplyScalar(.5);l.beam.scale.y=begin.distanceTo(end);l.beam.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),l.aim);
  }data.masks=masks;data.power=masks.map((m,i)=>(m&requirements[i])===requirements[i]);receivers.forEach((r,i)=>{r.gem.material.emissiveIntensity=data.power[i]?1:.1;r.light.intensity=data.power[i]?4:.3;r.wire.material.color.setHex(data.power[i]?receiverColors[i]:0x40565f);});return data.power;}
  function placeInitial(){lamps.forEach((l,i)=>{const d=definitions[i];if(!d.start)return;l.pos.set(d.start.x,GROUND_Y,d.start.z);l.mode='ground';l.target=d.start.target;l.aim.copy(receiverPositions[d.start.target]).sub(l.pos).normalize();l.fall.v=0;});}
  function reset(){data.held=-1;data.done=false;data.falls=0;vy=0;state.paused=state.won=false;state.lampMode='home';keys.clear();lamps.forEach(l=>{l.pos.copy(l.home);l.mode='home';l.aim.set(0,-.4,-1).normalize();l.fall.v=0;});placeInitial();setActor(world(new T.Vector3(0,0,4.8)));trace();data.bridges=[1,1];bridgeGroups.forEach(g=>g.position.y=0);data.gate=0;gate.position.y=0;document.getElementById('overlay').hidden=true;}
  function tick(dt){if(state.paused)return;const forward=camera.getWorldDirection(new T.Vector3()).setY(0).normalize(),right=new T.Vector3().crossVectors(forward,new T.Vector3(0,1,0)),move=new T.Vector3();if(keys.has('KeyW')||keys.has('ArrowUp'))move.add(forward);if(keys.has('KeyS')||keys.has('ArrowDown'))move.sub(forward);if(keys.has('KeyD')||keys.has('ArrowRight'))move.add(right);if(keys.has('KeyA')||keys.has('ArrowLeft'))move.sub(right);if(move.lengthSq()){move.normalize();avatar.rotation.y=Math.atan2(move.x,move.z);if(data.held>=0)lamps[data.held].aim.copy(move);}const speed=keys.has('ShiftLeft')?3.7:2.6;vy-=18*dt;capsule.translate(new T.Vector3(move.x*speed*dt,vy*dt,move.z*speed*dt));let ground=collide(staticTree);bridgeTrees.forEach((tree,i)=>{if(data.bridges[i]>.94)ground=collide(tree)||ground;});if(data.gate<.85)ground=collide(gateTree)||ground;if(ground)vy=Math.max(0,vy);state.actor.copy(capsule.start).sub(new T.Vector3(0,.24,0));avatar.position.copy(state.actor);if(state.actor.y< -1.8){data.falls++;vy=0;setActor(world(new T.Vector3(0,0,4.8)));toast('水流送你回到入口，已安放的光仍在');}
    for(const l of lamps)if(l.mode==='falling'){const p=world(l.pos),result=api.stepFall(p,l.fall,dt);l.pos.copy(p).sub(offset);if(result==='landed'){l.mode='ground';const landed=nearestVisibleTarget(l.pos,receiverPositions,ray,opticalTree,world);if(landed){l.aim.copy(landed).sub(l.pos);l.aim.y=0;l.aim.normalize();}}else if(result==='lost'){l.pos.copy(l.home);l.mode='home';l.aim.set(0,-.4,1).normalize();l.fall.v=0;toast(`${l.name}光回到了原来的灯台`);}}
    trace();data.bridges.forEach((v,i)=>{data.bridges[i]+=T.MathUtils.clamp((data.power[i]?1:0)-v,-dt/1.3,dt/1.3);bridgeGroups[i].position.y=-1.35*(1-data.bridges[i]);});const ready=data.power.every(Boolean);data.gate+=T.MathUtils.clamp((ready?1:0)-data.gate,-dt/1.1,dt/1.1);gate.position.y=-2.8*data.gate;const p=localActor();if(!ready&&data.gate<.85&&p.z< -13.6&&p.z> -14.55)setActor(world(new T.Vector3(p.x,0,-13.5)));if(ready&&data.gate>.85&&p.z< -15.05&&Math.abs(p.x)<3&&p.y>-.3){data.done=true;state.won=state.paused=true;keys.clear();api.finish();}}
  function hud(){const $=id=>document.getElementById(id);$('objective').textContent=data.power.every(Boolean)?'穿过白光之门':lamps[2].target===2?'让两段通路同时保持供能':lamps[1].target===1?'将腾出的白光送往尽头':'接续供能，取回白光';$('power').querySelector('span').textContent=`前桥 ${data.power[0]?'亮':'暗'} · 后桥 ${data.power[1]?'亮':'暗'} · 白锁 ${data.power[2]?'亮':'暗'}`;$('power').classList.toggle('on',data.power.every(Boolean));$('lampState').textContent=data.held>=0?`${lamps[data.held].name}光 · 随身`:'绿 → 青 → 白';$('inventory').classList.toggle('active',data.held>=0);setColorOrbits(data.held>=0?lamps[data.held].mask:0);$('location').textContent=localActor().z< -10?'白光圣所':localActor().z< -3?'青光中庭':'续光水廊';const a=action();$('context').style.display=a?'block':'none';$('interact').textContent=a?.kind==='pickup'?`提起${lamps[a.lamp].name}光`:a?.kind==='dock'?'留在灯座':'放下光';}
  return {root,offset,data,lamps,receivers,receiverPositions,bridgeGroups,goal:world(new T.Vector3(0,.6,-15.35)),world,localActor,reset,tick,interact,trace,aim,hud,focus(){const p=localActor();aim(receiverPositions[p.z< -10?2:p.z< -3?1:0]);}};
}
